### ISSUE TITLE
compatibility with dc conversion

### ISSUE THREAD

**Issue by nathanlycan** [PiKeyAr/sadx-hd-gui#13]
![Sonic Adventure 8_1_2022 12_44_06 PM](https://user-images.githubusercontent.com/73799396/182221599-1bb90a13-2226-4eec-8c8d-d4f5cb49377b.png)

this happens when i use dc conversion mod and this together

**Comment by nathanlycan** [comment]
the 2 eggman logos is what im referring to

**Comment by PiKeyAr** [comment]
Thanks for the report. This should now be fixed in DC Conversion.
