### ISSUE TITLE
Black line above Rings HUD

### ISSUE THREAD

**Issue by RetroForeverDev** [PiKeyAr/sadx-hd-gui#15]
if Rings are obtained in Adventure Fields with this mod on, the HUD will appear as intended, but with a small black line above it.
![sonic_h7bnKJt9uA](https://user-images.githubusercontent.com/79285355/200639309-7f7a1c47-0d3b-4ecf-af3d-eb07e877aa18.png)
as far as I can tell, this is something specific to when the Rings appear without the other HUD elements above

**Comment by RetroForever** [comment]
[this commit](https://github.com/X-Hax/sadx-hd-gui/commit/30ce3a7b098cf71aa4c38abf67ddbf6bcc983887) fixed the issue. ty!

**Comment by PiKeyAr** [comment]
This is a texture filtering artifact that also affects the vanilla PC version when "force texture filtering" is enabled in the Mod Loader. It's rather difficult to fix without compromises such as editing the texture, which would make it look different in Action Stages. Anyway I've been using a workaround which should fix it in most situations, and I've increased the offset in the current version. It might make the ring top look cut off though.
