### ISSUE TITLE
Game Over screen is not properly scaled in Japanese

### ISSUE THREAD

**Issue by hankju84** [PiKeyAr/sadx-hd-gui#16]
When I changed text language into Japanese, Game Over screen is not properly scaled like this. English is okay.
![71250_20240410171502_1](https://github.com/X-Hax/sadx-hd-gui/assets/73779442/2968e256-9740-445c-852d-52129a745a35)

**Comment by PiKeyAr** [comment]
Thanks for the report. This should be fixed in version 0.962.
