### ISSUE TITLE
Old recaps not being deleted

### ISSUE THREAD

**Issue by SeppukuTekkai** [PiKeyAr/sadx-hd-gui#3]
I found an issue where old recap text are not being deleted.

![repetition bug](https://user-images.githubusercontent.com/47348133/52262989-e0c15f80-28e2-11e9-87eb-33ae842a69c2.png)

It even happens across different saves and different characters.

![even across characters](https://user-images.githubusercontent.com/47348133/52263046-0189b500-28e3-11e9-82b2-99b6e84424c7.png)

Steps to reproduce:

1) Select a character to play, and make sure they have a recap.

2) Quit and return to menu without exiting the game.

3. Repeat step 1.

**Comment by PiKeyAr** [comment]
Should be fixed in [e49fb0d](https://github.com/PiKeyAr/sadx-hd-gui/commit/e49fb0dd7132cbc42df8133db92c704719caff60)
